name: Update Activity Graph

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: gabrielcattuzo
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: profile/activity-graph.svg
          options: theme=react-dark&hide_border=true&area=false

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/activity-graph.svg

          if git diff --cached --quiet; then
            echo "Nenhuma alteração encontrada."
          else
            git commit -m "update activity graph"
            git push
          fi